version: '3.8'

services:

  flask:
    restart: always
    container_name: api-beers
    build: ./api
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    build: ./sql
    restart: always
    container_name: db-beers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
     
    