version: '3.8'

services:

  flask:
    image: python
    restart: always
    container_name: api-beers
    build: api/Dockerfile
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    container_name: db-beers
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: beer.sql
     
    