version: '3.8'

services:

  flask:
    image: python
    restart: always
    container_name: api-beers
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:5000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    container_name: db-beers
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: beer.sql
     
    